import { RoleType } from "@prisma/client";
import type { TokenCardData } from "@/actions/dashboard";

// =============================================================================
// VCC — Accurate Member Data (sourced from VCC 2026 Master Spreadsheet)
// =============================================================================
// Cashout prices as of 2025-12-14 (latest weekly update)
// Token counts: instalment + carry-over from individual member sheets
// =============================================================================

export interface PaymentData {
  readonly reference: string;
  readonly date: string | null;
  readonly amount: number;
}

export interface DemoAccount {
  readonly userId: string;
  readonly membershipNo: string;
  readonly firstName: string;
  readonly lastName: string;
  readonly role: RoleType;
  readonly password: string;
  readonly accountValue: string;
  readonly tokens: ReadonlyArray<TokenCardData>;
  readonly payments: ReadonlyArray<PaymentData>;
}

// Current weekly cashout prices (ZAR) — updated 2025-12-14
const CASHOUT_PRICES: Record<string, number> = {
  ENTRY: 657.56,
  SILVER: 1318.81,
  GOLD: 2656.9,
  PLATINUM: 10668.75,
  DIAMOND: 26773.91,
  GROUP_1: 7993.2,
  GROUP_2: 24070.28,
  GROUP_3: 53635.26,
};

export { CASHOUT_PRICES };

// ---------------------------------------------------------------------------
// Member Accounts — data from individual Excel member sheets
// ---------------------------------------------------------------------------

export const DEMO_ACCOUNTS: ReadonlyArray<DemoAccount> = [
  {
    userId: "demo-bwg2020m00000",
    membershipNo: "BWG2020M00000",
    firstName: "Venture Chain",
    lastName: "Capital",
    role: "SUPER_ADMIN" as RoleType,
    password: "password123",
    accountValue: "62837.32",
    tokens: [
      {
        tokenSerial: "VCC-CO-SI-00000-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00000-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00000-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00000-2",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-DIAMOND-BWG2020M00000-I0",
        tier: "DIAMOND",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "26773.91",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-DI-00000-0",
        tier: "DIAMOND",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "26773.91",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2020m00001",
    membershipNo: "BWG2020M00001",
    firstName: "Kgomotso Elias",
    lastName: "Nkabinde",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "33283.92",
    tokens: [
      {
        tokenSerial: "VCC-CO-SI-00001-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2020GT00001",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2020GT00002",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00001-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00001-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00001-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00001-1",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-25 00:00:00",
        amount: 500.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-26 00:00:00",
        amount: 500.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-25 00:00:00",
        amount: 500.0,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00002",
    membershipNo: "BWG2020M00002",
    firstName: "Sechaba Richard",
    lastName: "Mokoena",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "1318.81",
    tokens: [
      {
        tokenSerial: "VCC2021ST00007",
        tier: "SILVER",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 0,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2020m00003",
    membershipNo: "BWG2020M00003",
    firstName: "Omphile Neo",
    lastName: "Makiri",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "15982.56",
    tokens: [
      {
        tokenSerial: "VCC2025GT00053",
        tier: "GOLD",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2025GT00054",
        tier: "GOLD",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2024PT00004",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "10668.75",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-26 00:00:00",
        amount: 1500.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-05-02 00:00:00",
        amount: 2000.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-05-11 00:00:00",
        amount: 2000.0,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00004",
    membershipNo: "BWG2020M00004",
    firstName: "Thando",
    lastName: "Khoza",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "20615.82",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00004-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2021ST00001",
        tier: "SILVER",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 11,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2020GT00006",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00004-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00004-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00004-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-03-02 00:00:00",
        amount: 268.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-04-01 00:00:00",
        amount: 268.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-05-02 00:00:00",
        amount: 268.0,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00005",
    membershipNo: "BWG2020M00005",
    firstName: "Khothatso",
    lastName: "Dhlamini",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "16640.12",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00005-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2020GT00007",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00005-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00005-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-28 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-04-01 00:00:00",
        amount: 268.04,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-05-02 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00006",
    membershipNo: "BWG2020M00006",
    firstName: "Bhabile",
    lastName: "Mithani",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "5313.80",
    tokens: [
      {
        tokenSerial: "VCC2020GT00008",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022GT00036",
        tier: "GOLD",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-19 00:00:00",
        amount: 1000.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-19 00:00:00",
        amount: 1100.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-05-02 00:00:00",
        amount: 500.0,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00008",
    membershipNo: "BWG2020M00008",
    firstName: "Itumeleng",
    lastName: "Nkabinde",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "29308.21",
    tokens: [
      {
        tokenSerial: "VCC2020GT00010",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2020GT00011",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00008-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00008-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00008-1",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-25 00:00:00",
        amount: 500.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-26 00:00:00",
        amount: 500.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-25 00:00:00",
        amount: 575.0,
      },
      {
        reference: "PAYMENT 4",
        date: "2026-04-25 00:00:00",
        amount: 500.0,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00010",
    membershipNo: "BWG2020M00010",
    firstName: "Sydney",
    lastName: "Phillips",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "16640.12",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00010-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2020GT00013",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00010-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00010-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-03-02 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-31 00:00:00",
        amount: 482.56,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-25 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00011",
    membershipNo: "BWG2020M00011",
    firstName: "Mhleli",
    lastName: "Masondo",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "45925.35",
    tokens: [
      {
        tokenSerial: "VCC2021ET00004",
        tier: "ENTRY",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "657.56",
        installmentsPaid: 6,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-EN-00011-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-EN-00011-1",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-SI-00011-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2020GT00014",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 6,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022GT00027",
        tier: "GOLD",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 6,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00011-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00011-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2021PT00001",
        tier: "PLATINUM",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "10668.75",
        installmentsPaid: 6,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00011-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00011-1",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-25 00:00:00",
        amount: 1562.5,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-25 00:00:00",
        amount: 1562.5,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-29 00:00:00",
        amount: 1562.5,
      },
      {
        reference: "PAYMENT 4",
        date: "2026-04-29 00:00:00",
        amount: 1562.5,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00012",
    membershipNo: "BWG2020M00012",
    firstName: "Tankiso",
    lastName: "Makhetha",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "12603.97",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00012-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-SI-00012-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2020GT00015",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00012-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00012-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00012-2",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-27 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-25 00:00:00",
        amount: 550.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-24 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00013",
    membershipNo: "BWG2020M00013",
    firstName: "Mmuso Richard",
    lastName: "Mafisa",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "15982.56",
    tokens: [
      {
        tokenSerial: "VCC2020GT00016",
        tier: "GOLD",
        issueYear: 2020,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 7,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00013-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00013-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-03-03 00:00:00",
        amount: 1000.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-04-11 00:00:00",
        amount: 1200.0,
      },
    ],
  },
  {
    userId: "demo-bwg2020m00014",
    membershipNo: "BWG2020M00014",
    firstName: "Edzani",
    lastName: "Davhana",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "16640.12",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00014-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-GOLD-BWG2020M00014-I0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00014-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00014-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-04-04 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-05-02 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2021m00001",
    membershipNo: "BWG2021M00001",
    firstName: "Sanele",
    lastName: "Shibe",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "16640.12",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00001-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2021GT00001",
        tier: "GOLD",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 7,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00001-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00001-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-24 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-24 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-24 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2021m00002",
    membershipNo: "BWG2021M00002",
    firstName: "Erica",
    lastName: "Mthethwa",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "5952.07",
    tokens: [
      {
        tokenSerial: "VCC2021ET00001",
        tier: "ENTRY",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "657.56",
        installmentsPaid: 6,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2025ST00006",
        tier: "SILVER",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 6,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-SI-00002-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00002-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-03-31 00:00:00",
        amount: 150.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-04-30 00:00:00",
        amount: 150.0,
      },
    ],
  },
  {
    userId: "demo-bwg2021m00003",
    membershipNo: "BWG2021M00003",
    firstName: "Abram",
    lastName: "Magooa",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "11942.72",
    tokens: [
      {
        tokenSerial: "VCC2021ET00002",
        tier: "ENTRY",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "657.56",
        installmentsPaid: 4,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-EN-00003-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022GT00033",
        tier: "GOLD",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 4,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022GT00034",
        tier: "GOLD",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 4,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00003-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00003-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-24 00:00:00",
        amount: 1200.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-25 00:00:00",
        amount: 600.0,
      },
    ],
  },
  {
    userId: "demo-bwg2021m00005",
    membershipNo: "BWG2021M00005",
    firstName: "Martha Tshedi",
    lastName: "Makiri",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "9289.51",
    tokens: [
      {
        tokenSerial: "VCC2021ST00003",
        tier: "SILVER",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00005-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00005-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00005-2",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-20 00:00:00",
        amount: 125.0,
      },
    ],
  },
  {
    userId: "demo-bwg2021m00008",
    membershipNo: "BWG2021M00008",
    firstName: "Nokukhanya",
    lastName: "Dlamini",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "7290.17",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00008-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2021ST00005",
        tier: "SILVER",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00008-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00008-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-04-23 00:00:00",
        amount: 1000.0,
      },
    ],
  },
  {
    userId: "demo-bwg2021m00010",
    membershipNo: "BWG2021M00010",
    firstName: "Asavela",
    lastName: "Ludidi",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "14644.46",
    tokens: [
      {
        tokenSerial: "VCC-CO-SI-00010-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022GT00040",
        tier: "GOLD",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 6,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00010-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-25 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-25 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-25 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2021m00011",
    membershipNo: "BWG2021M00011",
    firstName: "Junior",
    lastName: "Mashigo",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "16640.12",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00011-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2021GT00002",
        tier: "GOLD",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00011-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00011-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-28 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-24 00:00:00",
        amount: 17.44,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-03-25 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 4",
        date: "2026-04-25 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2021m00012",
    membershipNo: "BWG2021M00012",
    firstName: "Susan",
    lastName: "Monyai",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "5294.51",
    tokens: [
      {
        tokenSerial: "VCC2021ST00008",
        tier: "SILVER",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-SI-00012-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00012-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2021m00013",
    membershipNo: "BWG2021M00013",
    firstName: "Mashudu",
    lastName: "Monyai",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "3314.46",
    tokens: [
      {
        tokenSerial: "VCC2021ET00006",
        tier: "ENTRY",
        issueYear: 2021,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "657.56",
        installmentsPaid: 4,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00013-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2022m00002",
    membershipNo: "BWG2022M00002",
    firstName: "Letlhogonolo Harold",
    lastName: "Phokela",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "5952.07",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00002-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022ST00002",
        tier: "SILVER",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 8,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-SI-00002-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00002-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-26 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-26 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-28 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2022m00003",
    membershipNo: "BWG2022M00003",
    firstName: "Mzwakhe",
    lastName: "Dhlamini",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "7947.73",
    tokens: [
      {
        tokenSerial: "VCC2023ET00025",
        tier: "ENTRY",
        issueYear: 2023,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "657.56",
        installmentsPaid: 3,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-EN-00003-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022ST00004",
        tier: "SILVER",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 3,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00003-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00003-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-02 00:00:00",
        amount: 300.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-05-02 00:00:00",
        amount: 300.0,
      },
    ],
  },
  {
    userId: "demo-bwg2022m00004",
    membershipNo: "BWG2022M00004",
    firstName: "Mfundo",
    lastName: "Masondo",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "11946.41",
    tokens: [
      {
        tokenSerial: "VCC-CO-SI-00004-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022GT00029",
        tier: "GOLD",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00004-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00004-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00004-2",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-26 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-26 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-24 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2022m00005",
    membershipNo: "BWG2022M00005",
    firstName: "Nommiselo Pretty",
    lastName: "Khoza",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "2656.90",
    tokens: [
      {
        tokenSerial: "VCC2022GT00032",
        tier: "GOLD",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 4,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-05 00:00:00",
        amount: 520.0,
      },
    ],
  },
  {
    userId: "demo-bwg2022m00011",
    membershipNo: "BWG2022M00011",
    firstName: "Dipontso",
    lastName: "Motepe",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "12603.97",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00011-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-SI-00011-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022GT00038",
        tier: "GOLD",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00011-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00011-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00011-2",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-03-03 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-04-07 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-05-06 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2022m00014",
    membershipNo: "BWG2022M00014",
    firstName: "Sinesipo",
    lastName: "Makaula",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "6632.61",
    tokens: [
      {
        tokenSerial: "VCC-CO-SI-00014-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2026GT00048",
        tier: "GOLD",
        issueYear: 2026,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00014-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-03-01 00:00:00",
        amount: 850.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-05-05 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2022m00016",
    membershipNo: "BWG2022M00016",
    firstName: "Thabo",
    lastName: "Segota",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "4633.27",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00016-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2022ST00010",
        tier: "SILVER",
        issueYear: 2022,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 6,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00016-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-04-23 00:00:00",
        amount: 170.0,
      },
    ],
  },
  {
    userId: "demo-bwg2023m00001",
    membershipNo: "BWG2023M00001",
    firstName: "Ashley",
    lastName: "Maredi",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "17958.92",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00001-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2025ST00006",
        tier: "SILVER",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2023GT00001",
        tier: "GOLD",
        issueYear: 2023,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2025GT00055",
        tier: "GOLD",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00001-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2023m00002",
    membershipNo: "BWG2023M00002",
    firstName: "Shannon",
    lastName: "Fortuin",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "2656.90",
    tokens: [
      {
        tokenSerial: "VCC2023GT00002",
        tier: "GOLD",
        issueYear: 2023,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 6,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-02-27 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 2",
        date: "2026-03-28 00:00:00",
        amount: 250.0,
      },
      {
        reference: "PAYMENT 3",
        date: "2026-04-28 00:00:00",
        amount: 250.0,
      },
    ],
  },
  {
    userId: "demo-bwg2024m00001",
    membershipNo: "BWG2024M00001",
    firstName: "Femida",
    lastName: "Razak",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "29965.77",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00001-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00001-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00001-1",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00001-2",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2024PT00010",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "10668.75",
        installmentsPaid: 1,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-PL-00001-0",
        tier: "PLATINUM",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "10668.75",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2024m00002",
    membershipNo: "BWG2024M00002",
    firstName: "Nontobeko",
    lastName: "Dlamini",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "7290.17",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00002-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-SI-00002-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2024GT00036",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 7,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00002-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2024m00003",
    membershipNo: "BWG2024M00003",
    firstName: "Amohelang",
    lastName: "Mafisa",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "7290.17",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00003-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-SI-00003-0",
        tier: "SILVER",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "1318.81",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2024GT00037",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 7,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00003-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2025m00001",
    membershipNo: "BWG2025M00001",
    firstName: "Michaela",
    lastName: "Fortuin",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "657.56",
    tokens: [
      {
        tokenSerial: "VCC2025ET00011",
        tier: "ENTRY",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "657.56",
        installmentsPaid: 10,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2025m00002",
    membershipNo: "BWG2025M00002",
    firstName: "Shamee",
    lastName: "Fortuin",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "8628.26",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00002-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2025GT00056",
        tier: "GOLD",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 1,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2025GT00057",
        tier: "GOLD",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 1,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00002-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
    ],
  },
  {
    userId: "demo-bwg2025m00003",
    membershipNo: "BWG2025M00003",
    firstName: "Craig",
    lastName: "Fortuin",
    role: "MEMBER" as RoleType,
    password: "password123",
    accountValue: "8628.26",
    tokens: [
      {
        tokenSerial: "VCC-CO-EN-00003-0",
        tier: "ENTRY",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "657.56",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2025GT00058",
        tier: "GOLD",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC2025GT00059",
        tier: "GOLD",
        issueYear: 2025,
        status: "ACTIVE",
        isCarryOver: false,
        currentCashoutValue: "2656.90",
        installmentsPaid: 5,
        installmentsTotal: 12,
      },
      {
        tokenSerial: "VCC-CO-GO-00003-0",
        tier: "GOLD",
        issueYear: 2024,
        status: "ACTIVE",
        isCarryOver: true,
        currentCashoutValue: "2656.90",
        installmentsPaid: 12,
        installmentsTotal: 12,
      },
    ],
    payments: [
      {
        reference: "PAYMENT 1",
        date: "2026-05-07 00:00:00",
        amount: 3547.4,
      },
    ],
  },
];
